vich_uploader:
    db_driver: orm

    mappings:
       bien_avatars:
           uri_prefix: /images/avatars
           upload_destination: '%kernel.project_dir%/public/images/avatars'

        #    inject_on_load: false
        #    delete_on_update: true
        #    delete_on_remove: true
